sudo: required
dist: trusty

before_install:
  - sudo apt-get install git wget -q -y

script:
        - DRY_RUN=true PYBOMBS_MIRROR_BASE_URL="http://mirrors.tuna.tsinghua.edu.cnm/pybombs" PYBOMBS_MIRROR_WORK_DIR=$(pwd) ./pybombs-mirror.sh

notifications:
  email:
    recipients:
      - scateu@gmail.com
