sudo: required
dist: trusty

before_install:
  - sudo apt-get install git wget -q -y

script:
  - ./10-retrieve-urls-from-recipes.sh
  - DRY_RUN=true ./20-fetch.sh
  - PYBOMBS_MIRROR_BASE_URL="http://mirrors.tuna.tsinghua.edu.cnm/pybombs" ./30-replace-recipes.sh

notifications:
  email:
    recipients:
      - scateu@gmail.com
